apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ingress-nginx
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
