apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: PMA_HOST
          value: mysql
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: phpmyadmin